# PyTorch basics

In [1]:
import torch

In [2]:
# Tensors
scalar = torch.tensor(6)
scalar.item()

vector = torch.tensor([1, 2, 3])
vector

matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix[2]


tensor([7, 8, 9])

In [ ]:
# Random tensors
random_tensor = torch.rand(1, 3, 4)
random_tensor
random_tensor.ndim
random_tensor.shape

# Zeros and Ones tensors
zero_tensor = torch.zeros(size=(3, 4), dtype=int)
ones_tensor = torch.ones(2, 5)

zero_tensor, ones_tensor
ones_tensor.dtype

torch.float32

In [ ]:
# Sorting
matrix = torch.tensor([[1, 2, -1],
                       [7, 8, 3],
                       [8, 4, 1]])
array = torch.tensor([3, 4, 7, 1, 0, 5])

sorted_array = torch.sort(array, -1, True) # True -> descending order

sorted_matrix = torch.sort(matrix, 0)
print(sorted_matrix)

torch.return_types.sort(
values=tensor([[ 1,  2, -1],
        [ 7,  4,  1],
        [ 8,  8,  3]]),
indices=tensor([[0, 0, 0],
        [1, 2, 2],
        [2, 1, 1]]))


In [ ]:
# zeros_like()
range_tensor = torch.arange(0, 10, 3)
range_tensor

zero_like_tensor = torch.zeros_like(input=range_tensor) # zero tensor of same shape as of input
zero_like_tensor

tensor([0, 0, 0, 0])

In [51]:
# datatype
tensor_float32_bit = torch.tensor([19.1234567890, 2.1234567890, 3.1234567890])
tensor_float32_bit.dtype

tensor_float64_bit = tensor_float32_bit.type(torch.float64)
tensor_float64_bit

tensor_float32_bit * tensor_float64_bit

tensor([365.7066,   4.5091,   9.7560], dtype=torch.float64)

In [61]:
# tensor attributes
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"datatype - {some_tensor.dtype}")
print(f"shape - {some_tensor.shape}")
print(f"device - {some_tensor.device}")
print(f"dimension - {some_tensor.ndim}")

tensor([[0.9150, 0.1398, 0.2790, 0.1015],
        [0.9641, 0.0729, 0.7750, 0.9356],
        [0.8323, 0.4740, 0.4210, 0.5290]])
datatype - torch.float32
shape - torch.Size([3, 4])
device - cpu
dimension - 2


In [6]:
# matrix multiplication
matrix1 = torch.tensor([[1, 2, 3],
                       [0, 1, 5]])
matrix2 = torch.tensor([[3, 1, 5], [0, 8, 6], [9, 5, 9]])

matrix_multiplication = torch.matmul(matrix1, matrix2)

# print(f"matrix1 shape = {matrix1.shape}\nmatrix2 shape = {matrix2.shape}\nMultiplied matrix shape = {matrix_multiplication.shape}")
# print(matrix_multiplication)

# print(torch.multiply(torch.tensor([1, 2, 3]), torch.tensor([0, 9, 6])))

# element wise multiplication
t1 = torch.tensor([1, 2, 4])
t2 = torch.tensor([3, 4, 5])
t1 * t2

torch.mm(matrix1, matrix2) # alaias for matmul

# transpose
matrix1.T
matrix2.T

tensor([[3, 0, 9],
        [1, 8, 5],
        [5, 6, 9]])

In [35]:
# min, max, mean, sum

tensor_1 = torch.tensor([[7, 5, 1], [8, 0, 1], [- 1, 7, 9]])
torch.min(tensor_1, dim=1) # min value from each row
torch.min(tensor_1, dim=0) # min value from each column
torch.min(tensor_1) # min value from overall tensor

torch.max(tensor_1, dim=1) # max value from each row
torch.max(tensor_1, dim=0) # max value from each column
torch.max(tensor_1) # max value from overall tensor

torch.mean(tensor_1, dim=1, dtype=torch.float32) # avg of each row
torch.mean(tensor_1, dim=0, dtype=torch.float32) # avg of each column
torch.mean(tensor_1, dtype=torch.float32) # avg of whole tensor

torch.sum(tensor_1, dim=1) # sum of each row
torch.sum(tensor_1, dim=0) # sum of each column
torch.sum(tensor_1) # sum of whole tensor

# can also use them as object methods
tensor_1.min(), tensor_1.max(), tensor_1.mean(dtype=torch.float32), tensor_1.sum()
# index of min/max
tensor_1.argmin(dim=1), tensor_1.argmax(dim=0)



(tensor([2, 1, 0]), tensor([1, 2, 2]))

In [50]:
# reshape
t = torch.arange(0, 8)
t
t_reshaped = t.reshape(4, 2)
t_reshaped
another_t = torch.tensor([[2, 2, 8, 5], [9, 8, 0, 1]])
t.reshape_as(another_t)

# view -  a view of a tensor shares the same memory as the tensor
# i.e., chaning the view changes the original tensor
view_of_t = t.view(4, 2)
view_of_t[0, 0] = 99
t 

# stacking
matrix1 = torch.tensor([[1, 2, -1],
                       [7, 8, 3],
                       [8, 4, 1]])

new_row = torch.tensor([0, 0, 0])
new_matrix = torch.vstack((new_row, matrix1)) # vstack - stacks row
new_matrix

another_matrix = torch.tensor([[3, 3], [3, 3], [3, 3]])
combined_col_matrix = torch.hstack((matrix1, another_matrix)) # hstack - stacks col
combined_col_matrix


tensor([[ 1,  2, -1,  3,  3],
        [ 7,  8,  3,  3,  3],
        [ 8,  4,  1,  3,  3]])

In [ ]:
# squeeze, unsqueeze
matrix_another_one = torch.rand(1, 2, 3, 4, 1, 1)

squeezed = torch.squeeze(matrix_another_one) # removes all single dimensions
squeezed.shape
# unsqueeze adds a single dimension at a specified dim

# permute
random_t = torch.rand(2, 5, 1)
permuted = torch.permute(random_t, (1, 2, 0)) # rearranges the dimensions
permuted.shape # permuted is a view of original tensor - shares the same memory as original tensor

torch.Size([5, 1, 2])

# PyTorch and NumPy

In [72]:
# numpy array to tensor
import numpy as np 

array = np.arange(1., 11.)
tensor = torch.from_numpy(array).type(torch.float32)
array,array.dtype, tensor, tensor.dtype
# numpy has default dtype as float64 and pytorch has float32, make sure to change dtype if required

tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor, numpy_tensor.dtype


(tensor([1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

# Reproducibility

In [ ]:
RANDOM_SEED = 82

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(4, 3)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(4, 3)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.4578, 0.5315, 0.6431],
         [0.1698, 0.7182, 0.8449],
         [0.1788, 0.5927, 0.3971],
         [0.8382, 0.5383, 0.2787]]),
 tensor([[0.4578, 0.5315, 0.6431],
         [0.1698, 0.7182, 0.8449],
         [0.1788, 0.5927, 0.3971],
         [0.8382, 0.5383, 0.2787]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]))